name = "Microscaling"
uuid = "da1daca8-4fb4-4ba0-bee1-16070df54f00"
authors = ["Anton Oresten <antonoresten@proton.me> and contributors"]
version = "0.0.1"

[deps]
Einops = "e3ce28c8-8bfb-4704-8add-e3e7f14b55c9"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Microfloats = "31c70f10-a750-4521-b13c-797315ae2933"

[compat]
Einops = "0.1.9"
FixedPointNumbers = "0.8.5"
Microfloats = "0.0.5"
julia = "1.10"
