name = "Microscaling"
uuid = "da1daca8-4fb4-4ba0-bee1-16070df54f00"
authors = ["Anton Oresten <antonoresten@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
